### ISSUE TITLE
Smartphone: Partner and Contribuisci

### ISSUE THREAD

**Issue by madeincima** [tis-innovation-park/cleanroads-map#9]
I'd suggest to move this info in the blue panel which becomes visible clicking the menu icon, underneath the legend. They are probably not that important to cover such a big part of the map...

**Comment by bertolla** [comment]
As soon as Roberto gives me the ok for it (depending on the importance of the info), I will change it

**Comment by rcavaliere** [comment]
You are right for the "Partner" icon, but the "Contribuisci" one is at least during this winter very important for us since we want users to give us a feedback. Could we include the "Partner" info underneath the legend and raise the icon "Contribuisci" (where now the "Partner" icon is)? In this way we won't disturb too much the visualization of the stations on the map
